# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DeviceIdentifyGPRCService.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'DeviceIdentifyGPRCService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x44\x65viceIdentifyGPRCService.proto\x12\x12\x44\x65viceIdentifyGPRC\",\n\x05paths\x12\x11\n\tmodelpath\x18\x01 \x01(\t\x12\x10\n\x08\x66ilepath\x18\x02 \x01(\t\"2\n\ridentifyValue\x12\x0e\n\x06mValue\x18\x01 \x01(\t\x12\x11\n\tvalueType\x18\x02 \x01(\x05\";\n\rlocationValue\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01w\x18\x03 \x01(\x05\x12\t\n\x01h\x18\x04 \x01(\x05\x32\xb3\x01\n\x19\x44\x65viceIdentifyGPRCService\x12J\n\x08Identify\x12\x19.DeviceIdentifyGPRC.paths\x1a!.DeviceIdentifyGPRC.identifyValue\"\x00\x12J\n\x08location\x12\x19.DeviceIdentifyGPRC.paths\x1a!.DeviceIdentifyGPRC.locationValue\"\x00\x42\x43\n&com.robot.robotGrpc.DeviceIdentifyGPRCB\x12\x44\x65viceIdentifyGPRCP\x01\xa2\x02\x02\x44Ib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DeviceIdentifyGPRCService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.robot.robotGrpc.DeviceIdentifyGPRCB\022DeviceIdentifyGPRCP\001\242\002\002DI'
  _globals['_PATHS']._serialized_start=55
  _globals['_PATHS']._serialized_end=99
  _globals['_IDENTIFYVALUE']._serialized_start=101
  _globals['_IDENTIFYVALUE']._serialized_end=151
  _globals['_LOCATIONVALUE']._serialized_start=153
  _globals['_LOCATIONVALUE']._serialized_end=212
  _globals['_DEVICEIDENTIFYGPRCSERVICE']._serialized_start=215
  _globals['_DEVICEIDENTIFYGPRCSERVICE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
